
; > ===================== ;
;   Modality definitions  ;
; ===================== > ;
;
; > –––––––––––––––––––––––––––––––––––––––––––––––––– ;
;   Rexist (really exists) modality from Hobbs' logic  ;
; –––––––––––––––––––––––––––––––––––––––––––––––––– < ;

(= (ct-modality) rexist)

; > ––––––––––––––––––– ;
;   Deontic modalities  ;
; ––––––––––––––––––– < ;

(= (ct-modality) obligatory)
(= (ct-modality) permitted)
(= (ct-modality) optional)
